version: '3.8'

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  server:
    build:
      context: ./server
    restart: always
    networks:
        default:
            ipv4_address: 172.20.0.2
    ports:
      - "3000:3000"               # host_port:container_port
    env_file:
      - ./server/env.list

  client:
    build:
      context: ./client
    restart: always
    networks:
        default:
            ipv4_address: 172.20.0.3
    ports:
      - "8080:80"
    depends_on:
      - server
